### PR TITLE
Allow installing newer doctrine dependencies

### PR DESCRIPTION
**Pull request by NoResponseMate**

### CODE REVIEW

**Comment by loevgaard** [comment]
Hi, @NoResponseMate 

Thanks for your contribution.

Do you think you can make it build or at least the static analysis? So we don't release something that doesn't work with deps.

**Comment by loevgaard** [comment]
Ping me on Sylius slack if I am unresponsive :)

**Comment by NoResponseMate** [comment]
No worries, figuring out how to fix it took a bit and it's pretty late, so no rush 👋

**Comment by loevgaard** [comment]
Thank you 🎉

**Pull request merged**
